import json
import datetime

def generate_marathon_plan():
    # Load sources
    with open("plan.json", "r") as f:
        plan_data = json.load(f)
    
    try:
        with open("actuals.json", "r") as f:
            actuals_data = json.load(f)
    except:
        actuals_data = []

    # Get AWST today for comparison (UTC+8)
    awst_now = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=8)
    today_str = awst_now.strftime("%Y-%m-%d")

    actuals_by_date = {}
    for act in actuals_data:
        date = act["date"]
        if date not in actuals_by_date:
            actuals_by_date[date] = []
        actuals_by_date[date].append(act)

    md_content = []
    md_content.append("# Marathon Plan (Jan 5 – Apr 12)")
    md_content.append("")
    md_content.append("> **Note:** This file is automatically generated from [plan.json](plan.json). Do not edit this file directly.")
    md_content.append("")
    
    # Generate Table
    header = "| Week Starting | Mon | Tue | Wed | Thu | Fri | Sat | Sun | Stats (Planned / Actual / Proj) |"
    separator = "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |"
    md_content.append(header)
    md_content.append(separator)

    for i, week in enumerate(plan_data):
        date_obj = datetime.datetime.strptime(week["weekStarting"], "%Y-%m-%d")
        date_str = date_obj.strftime("%b %-d")
        week_num = i + 1
        
        row = [f"{date_str}<br>[Fridge](fridge/Week_{week_num:02d}.md)"]
        
        week_target_m = 0
        week_actual_m = 0
        week_remaining_m = 0
        
        for day in ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]:
            day_data = week["days"][day]
            day_date = day_data["date"]
            day_workouts = day_data["workouts"]
            
            cell_content = []
            
            # Planned
            if not day_workouts:
                cell_content.append("Rest")
            else:
                workout_names = []
                for w in day_workouts:
                    workout_names.append(w["name"])
                    dist = w.get("distance_m", 0)
                    week_target_m += dist
                    if day_date > today_str:
                        week_remaining_m += dist
                cell_content.append("<br>".join(workout_names))

            # Actual
            day_actuals = actuals_by_date.get(day_date, [])
            for act in day_actuals:
                if act.get("type") == "running":
                    dist = act.get("distance_m", 0)
                    week_actual_m += dist
                    dist_km = dist / 1000
                    cell_content.append(f"**✓ {dist_km:.1f}k**")
            
            row.append(" ".join(cell_content))
        
        target_km = week_target_m / 1000
        actual_km = week_actual_m / 1000
        projected_km = (week_actual_m + week_remaining_m) / 1000
        
        stats_str = f"Target: **{target_km:.0f}k**<br>Actual: **{actual_km:.1f}k**<br>Proj: **{projected_km:.1f}k**"
        row.append(stats_str)
        
        md_content.append(f"| {' | '.join(row)} |")

    md_content.append("")
    md_content.append("---")
    md_content.append("")
    
    # Static Sections
    static_sections = """
## Target Training Paces
- **Easy / Recovery:** 5:45 – 6:15 min/km
- **Marathon Pace (MP):** 5:30 – 5:40 min/km (Sub-4 Goal)
- **Steady / Aerobic Power:** 5:10 – 5:20 min/km
- **Threshold:** 4:40 – 4:50 min/km

## "Cramp-Proof" Strength Routine
*Perform 2-3 times per week (e.g., Tue/Sat).*
1. **Weighted Calf Raises:** 3 x 15 reps (Slow, 2s pause at top). *Critical for 97kg frame.*
2. **Bulgarian Split Squats:** 3 x 10 per leg (Quad resilience).
3. **Tibialis Raises:** 3 x 20 (Shin protection).
4. **Plank with Leg Lifts:** 3 x 60s (Core stability).

## Fueling Strategy (The 90/900 Rule)
- **Target:** 90g Carbs / 900mg Sodium per hour.
- **Products:** Bix 40g/30g salted gels + Bix carb drink mix.
- **Practice:** Use on all Sunday runs >20km with Salomon trail vest.

## Wednesday Double Strategy (Injury Prevention)
To safely manage the AM/PM double sessions, we use a "Steady-to-Threshold" progression:
- **Weeks 1-2:** AM session is 100% **Steady** (5:10-5:20). Focus on aerobic power without the high mechanical stress of threshold.
- **Weeks 3-8:** Introduce **Threshold blocks** (4:40-4:50) in the middle of the AM run.
- **Weeks 10-11:** Full **Threshold** AM sessions only once the body has adapted to the double-day volume.
- **Rule of Thumb:** If you feel excessive fatigue or "heavy legs" on Wednesday morning, keep the entire AM run at **Easy** pace (5:45+) to save yourself for the PM Club Intervals.

## Progressive Long Run (PLR) Execution
PLRs are your primary weapon against the 30km cramp. They teach your body to accelerate under fatigue.
- **First 1/3:** Super Easy (6:10 - 6:30 min/km). Wake the body up.
- **Middle 1/3:** Target Marathon Pace (5:45 min/km). Find your rhythm.
- **Final 1/3:** "The Attack" (5:20 - 5:35 min/km). Focus on tall form and high cadence.

## Key Workout: "The Attack" (Mar 9)
This is a 32km run with a massive 15km block at **5:35 min/km** in the middle. 
- **Goal:** Simulate the "dead leg" feeling of the marathon and push through it using your Bix fueling strategy.
- **Mental Focus:** This is where you prove to yourself that the 30km mark is just a number.

## Parkrun Sub-22 Strategy
To break 22 minutes (4:24 min/km pace) while training for a marathon:
- **Tempo PR:** Run at **Threshold pace (4:40-4:50)**. This builds strength without the "redline" fatigue that could ruin your Sunday long run.
- **Sub-22 Attempt:** Target **4:20-4:24 min/km**. These are scheduled on weeks where the Sunday load is slightly lower or during recovery weeks.
- **Warm-up/Cool-down:** Always include at least 1-2km of very easy jogging before and after to reach the total Saturday volume and flush the legs.
- **Consistency:** Use the Tempo PRs to practice your high-cadence turnover and mental toughness.
"""
    md_content.append(static_sections.strip())

    with open("marathon_plan.md", "w") as f:
        f.write("\n".join(md_content))
    
    print("Successfully generated marathon_plan.md from plan.json")

def generate_context_md():
    # Load the source of truth
    with open("context.json", "r") as f:
        data = json.load(f)

    md = []
    # Using AWST for current year reference if needed, but simplified here
    current_year = datetime.datetime.now().year
    md.append(f"# Training Context: {data['project']['event']} {current_year}")
    md.append("")
    md.append("> **Note:** This file is automatically generated from [context.json](context.json). Do not edit this file directly.")
    md.append("")
    
    md.append("## Runner Profile")
    md.append(f"- **Age/Gender:** {data['runner']['age']}-year-old {data['runner']['gender']}")
    md.append(f"- **Physicals:** {data['runner']['height_cm']}cm, {data['runner']['weight_kg']['current']}kg (Current) -> **Target: {data['runner']['weight_kg']['target']}kg** by Race Day.")
    md.append("- **Personal Bests:**")
    for pb, val in data['runner']['personalBests'].items():
        md.append(f"  - {pb}: {val}")
    md.append("")

    md.append("## Goal")
    md.append(f"- **Primary Event:** {data['project']['event']}")
    md.append(f"- **Date:** {data['project']['eventDate']}")
    md.append(f"- **Target Time:** {data['project']['goal']}")
    md.append("")

    md.append("## Training Overview")
    md.append(f"- **Duration:** {data['planOverview']['durationWeeks']} weeks")
    md.append(f"- **Peak Volume:** {data['planOverview']['peakVolume_km']} km")
    md.append(f"- **Frequency:** {data['planOverview']['frequencyDaysPerWeek']} days/week")
    md.append(f"- **Strategy:** {data['planOverview']['strategy']}")
    md.append("")

    md.append("## Key Milestones")
    for m in data['milestones']:
        md.append(f"- **{m['name']}:** {m['date']} ({m['description']})")
    md.append("")

    md.append("## Training Philosophy & Strategy")
    md.append("- **Cramp Prevention:**")
    md.append(f"  - **Mechanical:** {data['philosophy']['crampPrevention']['mechanical']}")
    md.append(f"  - **Metabolic:** {data['philosophy']['crampPrevention']['metabolic']}")
    md.append(f"  - **Fueling:** {data['philosophy']['crampPrevention']['fueling']}")
    md.append("- **Weekly Structure:**")
    for day, desc in data['philosophy']['weeklyStructure'].items():
        md.append(f"  - **{day}:** {desc}")
    md.append("")

    md.append("## Current Status")
    md.append(f"- **Date:** {data['status']['lastUpdated']}")
    md.append(f"- **Phase:** {data['status']['phase']}")
    md.append(f"- **Architecture:** {data['status']['architecture']}")
    md.append(f"- **Garmin Sync:** {data['status']['garminSync']}")
    md.append(f"- **Tooling:** {data['status']['tooling']}")
    md.append(f"- **Next Action:** {data['status']['nextAction']}")

    with open("context.md", "w") as f:
        f.write("\n".join(md))
    
    print("Successfully generated context.md from context.json")

if __name__ == "__main__":
    generate_marathon_plan()
    generate_context_md()
