import json
from datetime import datetime

def generate_markdown():
    # Load the source of truth
    with open("plan.json", "r") as f:
        plan_data = json.load(f)

    md_content = []
    md_content.append("# Marathon Plan (Jan 5 – Apr 12)")
    md_content.append("")
    md_content.append("> **Note:** This file is automatically generated from [plan.json](plan.json). Do not edit this file directly.")
    md_content.append("")
    
    # Generate Table
    header = "| Week Starting | Mon | Tue | Wed (AM/PM) | Thu (Trail) | Fri | Sat | Sun (Long Run) | Total |"
    separator = "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |"
    md_content.append(header)
    md_content.append(separator)

    for week in plan_data:
        date_obj = datetime.strptime(week["weekStarting"], "%Y-%m-%d")
        date_str = date_obj.strftime("%b %-d")
        
        row = [date_str]
        total_dist = 0
        
        for day in ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]:
            day_workouts = week["days"][day]["workouts"]
            if not day_workouts:
                row.append("Rest")
            else:
                workout_names = []
                for w in day_workouts:
                    workout_names.append(w["name"])
                    total_dist += w["distance_m"]
                row.append(" / ".join(workout_names))
        
        row.append(f"{int(total_dist/1000)}k")
        md_content.append(f"| {' | '.join(row)} |")

    md_content.append("")
    md_content.append("---")
    md_content.append("")
    
    # Static Sections
    static_sections = """
## Target Training Paces
- **Easy / Recovery:** 5:45 – 6:15 min/km
- **Marathon Pace (MP):** 5:30 – 5:40 min/km (Sub-4 Goal)
- **Steady / Aerobic Power:** 5:10 – 5:20 min/km
- **Threshold:** 4:40 – 4:50 min/km

## "Cramp-Proof" Strength Routine
*Perform 2-3 times per week (e.g., Tue/Sat).*
1. **Weighted Calf Raises:** 3 x 15 reps (Slow, 2s pause at top). *Critical for 97kg frame.*
2. **Bulgarian Split Squats:** 3 x 10 per leg (Quad resilience).
3. **Tibialis Raises:** 3 x 20 (Shin protection).
4. **Plank with Leg Lifts:** 3 x 60s (Core stability).

## Fueling Strategy (The 90/900 Rule)
- **Target:** 90g Carbs / 900mg Sodium per hour.
- **Products:** Bix 40g/30g salted gels + Bix carb drink mix.
- **Practice:** Use on all Sunday runs >20km with Salomon trail vest.

## Wednesday Double Strategy (Injury Prevention)
To safely manage the AM/PM double sessions, we use a "Steady-to-Threshold" progression:
- **Weeks 1-2:** AM session is 100% **Steady** (5:10-5:20). Focus on aerobic power without the high mechanical stress of threshold.
- **Weeks 3-8:** Introduce **Threshold blocks** (4:40-4:50) in the middle of the AM run.
- **Weeks 10-11:** Full **Threshold** AM sessions only once the body has adapted to the double-day volume.
- **Rule of Thumb:** If you feel excessive fatigue or "heavy legs" on Wednesday morning, keep the entire AM run at **Easy** pace (5:45+) to save yourself for the PM Club Intervals.

## Progressive Long Run (PLR) Execution
PLRs are your primary weapon against the 30km cramp. They teach your body to accelerate under fatigue.
- **First 1/3:** Super Easy (6:10 - 6:30 min/km). Wake the body up.
- **Middle 1/3:** Target Marathon Pace (5:45 min/km). Find your rhythm.
- **Final 1/3:** "The Attack" (5:20 - 5:35 min/km). Focus on tall form and high cadence.

## Key Workout: "The Attack" (Mar 9)
This is a 32km run with a massive 15km block at **5:35 min/km** in the middle. 
- **Goal:** Simulate the "dead leg" feeling of the marathon and push through it using your Bix fueling strategy.
- **Mental Focus:** This is where you prove to yourself that the 30km mark is just a number.

## Parkrun Sub-22 Strategy
To break 22 minutes (4:24 min/km pace) while training for a marathon:
- **Tempo PR:** Run at **Threshold pace (4:40-4:50)**. This builds strength without the "redline" fatigue that could ruin your Sunday long run.
- **Sub-22 Attempt:** Target **4:20-4:24 min/km**. These are scheduled on weeks where the Sunday load is slightly lower or during recovery weeks.
- **Warm-up/Cool-down:** Always include at least 1-2km of very easy jogging before and after to reach the total Saturday volume and flush the legs.
- **Consistency:** Use the Tempo PRs to practice your high-cadence turnover and mental toughness.
"""
    md_content.append(static_sections.strip())

    with open("marathon_plan.md", "w") as f:
        f.write("\n".join(md_content))
    
    print("Successfully generated marathon_plan.md from plan.json")

if __name__ == "__main__":
    generate_markdown()
