"""add splits json

Revision ID: 1c9001194bfe
Revises: 1cd48c1e883a
Create Date: 2026-01-20 20:30:55.396643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c9001194bfe'
down_revision: Union[str, Sequence[str], None] = '1cd48c1e883a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actualactivity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('splits_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actualactivity', schema=None) as batch_op:
        batch_op.drop_column('splits_json')

    # ### end Alembic commands ###
