"""Add swim_zones_json to RunnerProfile

Revision ID: 1da6be737fa1
Revises: 7a54de9f2ce9
Create Date: 2026-01-28 23:12:53.819657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1da6be737fa1"
down_revision: Union[str, Sequence[str], None] = "7a54de9f2ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runnerprofile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "swim_zones_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runnerprofile", schema=None) as batch_op:
        batch_op.drop_column("swim_zones_json")

    # ### end Alembic commands ###
