"""Add ActualActivity

Revision ID: 35bbade6716a
Revises: 7032a5b17538
Create Date: 2026-01-15 15:08:53.041409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35bbade6716a'
down_revision: Union[str, Sequence[str], None] = '7032a5b17538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actualactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('average_pace_m_s', sa.Float(), nullable=True),
    sa.Column('average_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('average_power', sa.Float(), nullable=True),
    sa.Column('aerobic_te', sa.Float(), nullable=True),
    sa.Column('anaerobic_te', sa.Float(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('hr_zones_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pace_zones_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('power_zones_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actualactivity_activity_id'), 'actualactivity', ['activity_id'], unique=True)
    # Tables runnerprofile, runnerproject, weightentry already exist in DB
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('weightentry')
    # op.drop_table('runnerproject')
    # op.drop_table('runnerprofile')
    op.drop_index(op.f('ix_actualactivity_activity_id'), table_name='actualactivity')
    op.drop_table('actualactivity')
    # ### end Alembic commands ###
