"""Add swim_zones_json to RunnerProfile

Revision ID: 7a54de9f2ce9
Revises: ee4e0186557f
Create Date: 2026-01-28 23:12:12.223683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a54de9f2ce9'
down_revision: Union[str, Sequence[str], None] = 'ee4e0186557f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
