"""Remove weight tracking features

Revision ID: 9a4ad7fe5e8e
Revises: 1da6be737fa1
Create Date: 2026-02-03 16:55:52.309529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4ad7fe5e8e'
down_revision: Union[str, Sequence[str], None] = '1da6be737fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weightentry')
    with op.batch_alter_table('runnerprofile', schema=None) as batch_op:
        batch_op.drop_column('target_weight')
        batch_op.drop_column('current_weight')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runnerprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_weight', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('target_weight', sa.FLOAT(), nullable=False))

    op.create_table('weightentry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('date_recorded', sa.DATE(), nullable=False),
    sa.Column('weight_kg', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['runnerprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
