"""Add type column to RunnerPlan

Revision ID: ee4e0186557f
Revises: 1c9001194bfe
Create Date: 2026-01-28 22:31:33.561392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ee4e0186557f"
down_revision: Union[str, Sequence[str], None] = "1c9001194bfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runnerplan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="running",
            )
        )

    # Backfill existing rows so they have a consistent default type.
    op.execute("UPDATE runnerplan SET type = 'running' WHERE type IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runnerplan", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
