"""Add json fields to profile

Revision ID: f28be068126f
Revises: 773b1fa822cf
Create Date: 2026-01-20 15:49:08.890832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f28be068126f'
down_revision: Union[str, Sequence[str], None] = '773b1fa822cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runnerprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_zones_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fueling_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runnerprofile', schema=None) as batch_op:
        batch_op.drop_column('fueling_json')
        batch_op.drop_column('training_zones_json')

    # ### end Alembic commands ###
